export enum ServiceCategory {
  ROADSIDE_CAR = "ROADSIDE_CAR",
  ROADSIDE_BIKE = "ROADSIDE_BIKE",
  HOME_SERVICE = "HOME_SERVICE",
  TOWING = "TOWING",
  LUXURY = "LUXURY",
  GARAGE_LISTING = "GARAGE_LISTING",
  ELECTRIC_VEHICLE = "ELECTRIC_VEHICLE",
}